// 词库种子表 —— 真实高频学术/雅思常见词（综合 AWL 学术词表 + 雅思高频词整理）。
// 【释义待校对】：单词均为真实常用词，核心释义可靠；个别例句/次要词义如发现偏差请提出修正。
const SEED_WORDS = [
  { word: "abandon", pos: "v.", cn: "放弃；抛弃", ex: "They had to abandon the plan due to a lack of funds." },
  { word: "abolish", pos: "v.", cn: "废除（制度、法律）", ex: "The government decided to abolish the old tax system." },
  { word: "abstract", pos: "adj./n.", cn: "抽象的；摘要", ex: "The concept is too abstract for beginners to grasp." },
  { word: "absurd", pos: "adj.", cn: "荒谬的；可笑的", ex: "It would be absurd to blame the accident on bad luck." },
  { word: "abundant", pos: "adj.", cn: "丰富的；大量的", ex: "The region has abundant natural resources." },
  { word: "accelerate", pos: "v.", cn: "加速；促进", ex: "New technology can accelerate economic growth." },
  { word: "access", pos: "n./v.", cn: "进入；使用权；获取", ex: "Students need easy access to the library." },
  { word: "accessible", pos: "adj.", cn: "可进入的；易理解的", ex: "The website should be accessible to everyone." },
  { word: "accommodate", pos: "v.", cn: "容纳；适应", ex: "The hotel can accommodate up to 500 guests." },
  { word: "accompany", pos: "v.", cn: "陪伴；伴随", ex: "Heavy rain was accompanied by strong winds." },
  { word: "accomplish", pos: "v.", cn: "完成；实现", ex: "She accomplished her goal of running a marathon." },
  { word: "accountable", pos: "adj.", cn: "负有责任的", ex: "Managers are accountable for their decisions." },
  { word: "accumulate", pos: "v.", cn: "积累；积聚", ex: "Over the years she accumulated a vast collection of books." },
  { word: "accurate", pos: "adj.", cn: "准确的；精确的", ex: "The report must be accurate and up to date." },
  { word: "accuse", pos: "v.", cn: "指控；指责", ex: "He was accused of stealing money from the company." },
  { word: "achieve", pos: "v.", cn: "实现；达到", ex: "With hard work you can achieve almost anything." },
  { word: "acknowledge", pos: "v.", cn: "承认；致谢", ex: "He acknowledged that the report contained some errors." },
  { word: "acquire", pos: "v.", cn: "获得；习得", ex: "Children acquire language remarkably quickly." },
  { word: "adapt", pos: "v.", cn: "适应；改编", ex: "It takes time to adapt to a new culture." },
  { word: "addiction", pos: "n.", cn: "上瘾；沉迷", ex: "Smartphone addiction is a growing concern." },
  { word: "adequate", pos: "adj.", cn: "足够的；适当的", ex: "The funding is not adequate to complete the project." },
  { word: "adjacent", pos: "adj.", cn: "邻近的；毗连的", ex: "The hotel is adjacent to the railway station." },
  { word: "adjust", pos: "v.", cn: "调整；适应", ex: "You can adjust the seat to a comfortable position." },
  { word: "administer", pos: "v.", cn: "管理；执行", ex: "The fund is administered by a group of trustees." },
  { word: "admire", pos: "v.", cn: "钦佩；欣赏", ex: "I admire her courage and determination." },
  { word: "adopt", pos: "v.", cn: "采用；收养", ex: "The school adopted a new teaching method." },
  { word: "advance", pos: "v./n.", cn: "前进；进展；预先的", ex: "Recent advances in medicine have saved many lives." },
  { word: "advantage", pos: "n.", cn: "优势；好处", ex: "Speaking two languages is a real advantage." },
  { word: "adverse", pos: "adj.", cn: "不利的；负面的", ex: "Smoking has an adverse effect on health." },
  { word: "advertise", pos: "v.", cn: "做广告；宣传", ex: "Companies advertise their products on social media." },
  { word: "advertisement", pos: "n.", cn: "广告", ex: "I saw the advertisement in a magazine." },
  { word: "advisable", pos: "adj.", cn: "明智的；可取的", ex: "It is advisable to book your seat in advance." },
  { word: "advocate", pos: "v./n.", cn: "提倡；倡导者", ex: "Many experts advocate a balanced diet." },
  { word: "aesthetic", pos: "adj.", cn: "美学的；审美的", ex: "The building has great aesthetic appeal." },
  { word: "affect", pos: "v.", cn: "影响", ex: "Lack of sleep can affect your concentration." },
  { word: "afford", pos: "v.", cn: "负担得起", ex: "Few families can afford to buy a house here." },
  { word: "aggregate", pos: "n./adj.", cn: "总数；合计的", ex: "The aggregate of all the scores gives the final result." },
  { word: "aggressive", pos: "adj.", cn: "好斗的；积极进取的", ex: "The company adopted an aggressive marketing strategy." },
  { word: "agriculture", pos: "n.", cn: "农业", ex: "Agriculture remains the main industry in the area." },
  { word: "aid", pos: "n./v.", cn: "援助；帮助", ex: "The country received financial aid after the disaster." },
  { word: "algorithm", pos: "n.", cn: "算法", ex: "Search engines use complex algorithms." },
  { word: "allege", pos: "v.", cn: "（无证据地）宣称", ex: "He is alleged to have taken the money." },
  { word: "alleviate", pos: "v.", cn: "减轻；缓和", ex: "The medicine helps to alleviate the pain." },
  { word: "allocate", pos: "v.", cn: "分配；拨出", ex: "The government allocated more money to education." },
  { word: "alter", pos: "v.", cn: "改变；修改", ex: "Nothing can alter the fact that he was wrong." },
  { word: "alternative", pos: "n./adj.", cn: "替代选择；可替代的", ex: "Solar power is a clean alternative to fossil fuels." },
  { word: "ambiguous", pos: "adj.", cn: "模棱两可的；含糊的", ex: "The wording of the rule is ambiguous." },
  { word: "ambition", pos: "n.", cn: "抱负；雄心", ex: "Her ambition is to become a doctor." },
  { word: "amend", pos: "v.", cn: "修正；修订", ex: "The law was later amended to protect workers." },
  { word: "ample", pos: "adj.", cn: "充足的；宽敞的", ex: "There is ample time to finish the test." },
  { word: "analyse", pos: "v.", cn: "分析", ex: "Scientists analyse the data to find patterns." },
  { word: "ancient", pos: "adj.", cn: "古代的；古老的", ex: "The museum displays ancient Egyptian art." },
  { word: "annual", pos: "adj.", cn: "每年的；年度的", ex: "The company holds an annual meeting in spring." },
  { word: "anonymous", pos: "adj.", cn: "匿名的", ex: "The donor wished to remain anonymous." },
  { word: "anticipate", pos: "v.", cn: "预期；预料", ex: "We anticipate strong demand for the product." },
  { word: "apparatus", pos: "n.", cn: "设备；器械", ex: "The lab is full of scientific apparatus." },
  { word: "apparent", pos: "adj.", cn: "明显的；表面上的", ex: "It soon became apparent that he was lying." },
  { word: "appeal", pos: "v./n.", cn: "呼吁；吸引力；上诉", ex: "The charity appealed to the public for donations." },
  { word: "applicable", pos: "adj.", cn: "适用的；可应用的", ex: "These rules are applicable to all students." },
  { word: "appoint", pos: "v.", cn: "任命；指定", ex: "She was appointed manager of the department." },
  { word: "appreciate", pos: "v.", cn: "欣赏；感激；体会", ex: "I really appreciate your help." },
  { word: "approach", pos: "v./n.", cn: "接近；方法；途径", ex: "We need a new approach to solving the problem." },
  { word: "appropriate", pos: "adj.", cn: "适当的；恰当的", ex: "Please wear appropriate clothing for the interview." },
  { word: "approve", pos: "v.", cn: "批准；赞成", ex: "The committee approved the new budget." },
  { word: "approximate", pos: "adj./v.", cn: "大约的；近似", ex: "The approximate cost is around 200 dollars." },
  { word: "arbitrary", pos: "adj.", cn: "任意的；武断的", ex: "The decision seemed completely arbitrary." },
  { word: "architecture", pos: "n.", cn: "建筑学；建筑风格", ex: "She studied modern architecture at university." },
  { word: "arise", pos: "v.", cn: "出现；发生", ex: "Problems may arise if we are not careful." },
  { word: "artificial", pos: "adj.", cn: "人造的；人工的", ex: "The lake is artificial, not natural." },
  { word: "aspect", pos: "n.", cn: "方面；层面", ex: "We must consider every aspect of the plan." },
  { word: "aspire", pos: "v.", cn: "渴望；立志", ex: "Many students aspire to study abroad." },
  { word: "assemble", pos: "v.", cn: "组装；集合", ex: "Workers assemble the cars on the production line." },
  { word: "assert", pos: "v.", cn: "断言；坚称", ex: "She asserted that the data were correct." },
  { word: "assess", pos: "v.", cn: "评估；估价", ex: "Teachers regularly assess students' progress." },
  { word: "asset", pos: "n.", cn: "资产；财富；有价值的人", ex: "Patience is a valuable asset in this job." },
  { word: "assign", pos: "v.", cn: "分配；指派", ex: "The teacher assigned us a difficult task." },
  { word: "assignment", pos: "n.", cn: "作业；任务", ex: "The teacher gave us a written assignment." },
  { word: "assist", pos: "v.", cn: "协助；帮助", ex: "A guide was there to assist the tourists." },
  { word: "associate", pos: "v.", cn: "联系；交往", ex: "People often associate red with danger." },
  { word: "assume", pos: "v.", cn: "假定；承担", ex: "We cannot assume that prices will stay the same." },
  { word: "assumption", pos: "n.", cn: "假设；假定", ex: "The plan is based on the assumption that prices will rise." },
  { word: "assure", pos: "v.", cn: "向…保证；使确信", ex: "I can assure you that the work will be done on time." },
  { word: "attach", pos: "v.", cn: "附上；系上；使依恋", ex: "Please attach your photo to the application form." },
  { word: "attain", pos: "v.", cn: "达到；获得", ex: "Few students attain such high scores." },
  { word: "attempt", pos: "v./n.", cn: "尝试；企图", ex: "She made several attempts to pass the exam." },
  { word: "attitude", pos: "n.", cn: "态度；看法", ex: "A positive attitude makes learning easier." },
  { word: "attribute", pos: "v./n.", cn: "把…归因于；特质", ex: "She attributes her success to hard work." },
  { word: "authentic", pos: "adj.", cn: "真实的；地道的", ex: "The restaurant serves authentic Italian food." },
  { word: "authority", pos: "n.", cn: "权威；当局；职权", ex: "The local authority is responsible for the roads." },
  { word: "automatic", pos: "adj.", cn: "自动的；无意识的", ex: "The doors open by an automatic sensor." },
  { word: "automation", pos: "n.", cn: "自动化", ex: "Automation has replaced many factory jobs." },
  { word: "available", pos: "adj.", cn: "可获得的；有空的", ex: "Tickets are available online and at the door." },
  { word: "aware", pos: "adj.", cn: "意识到的；知道的", ex: "Many people are not aware of the risks." },
  { word: "awkward", pos: "adj.", cn: "尴尬的；笨拙的；棘手的", ex: "There was an awkward silence after his question." },
  { word: "balance", pos: "n./v.", cn: "平衡；余额", ex: "It is important to keep a balance between work and rest." },
  { word: "ban", pos: "v./n.", cn: "禁止", ex: "The city decided to ban cars from the centre." },
  { word: "bankrupt", pos: "adj./v.", cn: "破产的", ex: "The firm went bankrupt during the crisis." },
  { word: "barrier", pos: "n.", cn: "障碍；屏障", ex: "Language can be a barrier to communication." },
  { word: "basis", pos: "n.", cn: "基础；依据", ex: "The decision was made on the basis of cost." },
  { word: "behalf", pos: "n.", cn: "代表（on behalf of）", ex: "She accepted the award on behalf of the team." },
  { word: "beneficial", pos: "adj.", cn: "有益的；有利的", ex: "Regular exercise is beneficial to health." },
  { word: "benefit", pos: "n./v.", cn: "益处；受益", ex: "Regular exercise benefits both body and mind." },
  { word: "bias", pos: "n./v.", cn: "偏见；偏向", ex: "The report showed a clear bias against women." },
  { word: "biodiversity", pos: "n.", cn: "生物多样性", ex: "Rainforests are rich in biodiversity." },
  { word: "bond", pos: "n./v.", cn: "纽带；债券；联结", ex: "There is a strong bond between the two sisters." },
  { word: "boost", pos: "v./n.", cn: "促进；提升", ex: "The new factory will boost the local economy." },
  { word: "boundary", pos: "n.", cn: "边界；界限", ex: "The river forms the boundary between the two countries." },
  { word: "breakthrough", pos: "n.", cn: "突破；重大进展", ex: "Scientists made a major breakthrough in cancer research." },
  { word: "brief", pos: "adj./n./v.", cn: "简短的；简报；简要介绍", ex: "He gave a brief summary of the report." },
  { word: "brilliant", pos: "adj.", cn: "出色的；明亮的", ex: "She came up with a brilliant idea." },
  { word: "budget", pos: "n./v.", cn: "预算", ex: "The project was completed within budget." },
  { word: "bulk", pos: "n.", cn: "大量；大部分；体积", ex: "The bulk of the work has already been done." },
  { word: "burden", pos: "n./v.", cn: "负担；重担", ex: "The cost of care is a heavy burden on families." },
  { word: "campaign", pos: "n./v.", cn: "运动；活动；战役", ex: "They launched a campaign to reduce plastic waste." },
  { word: "capable", pos: "adj.", cn: "有能力的；能干的", ex: "She is capable of handling the project alone." },
  { word: "capacity", pos: "n.", cn: "容量；能力", ex: "The stadium has a capacity of 60,000 people." },
  { word: "category", pos: "n.", cn: "类别；范畴", ex: "Books are divided into several categories." },
  { word: "cease", pos: "v.", cn: "停止；终止", ex: "The factory ceased production last year." },
  { word: "celebrity", pos: "n.", cn: "名人；名声", ex: "The restaurant is popular with celebrities." },
  { word: "censorship", pos: "n.", cn: "审查制度", ex: "There is strict censorship of the press." },
  { word: "census", pos: "n.", cn: "人口普查", ex: "A census is taken every ten years." },
  { word: "challenge", pos: "n./v.", cn: "挑战；质疑", ex: "Climate change is a global challenge." },
  { word: "characteristic", pos: "n./adj.", cn: "特征；特有的", ex: "Patience is a key characteristic of a good teacher." },
  { word: "charge", pos: "v./n.", cn: "收费；指控；充电；负责", ex: "The hotel charges extra for breakfast." },
  { word: "cite", pos: "v.", cn: "引用；举例", ex: "The author cited several studies to support the claim." },
  { word: "civil", pos: "adj.", cn: "公民的；民事的；文明的", ex: "Every citizen enjoys basic civil rights." },
  { word: "clarify", pos: "v.", cn: "澄清；阐明", ex: "Could you clarify what you mean by that?" },
  { word: "classic", pos: "adj./n.", cn: "经典的；典型的", ex: "This novel is a classic of English literature." },
  { word: "coherent", pos: "adj.", cn: "连贯的；条理清晰的", ex: "A good essay must present a coherent argument." },
  { word: "coincide", pos: "v.", cn: "同时发生；相一致", ex: "My holiday coincided with the festival." },
  { word: "collapse", pos: "v./n.", cn: "倒塌；崩溃", ex: "The old bridge collapsed during the flood." },
  { word: "colleague", pos: "n.", cn: "同事", ex: "She gets along well with her colleagues." },
  { word: "commit", pos: "v.", cn: "承诺；投入；犯（罪）", ex: "They committed themselves to finishing the work." },
  { word: "commodity", pos: "n.", cn: "商品；货物", ex: "Oil is an important commodity in world trade." },
  { word: "commute", pos: "v./n.", cn: "通勤", ex: "Many people commute to work by train." },
  { word: "compatible", pos: "adj.", cn: "兼容的；和谐的", ex: "The software is compatible with most computers." },
  { word: "compensate", pos: "v.", cn: "补偿；弥补", ex: "Nothing can compensate for the loss of a friend." },
  { word: "compete", pos: "v.", cn: "竞争；比赛", ex: "Small shops find it hard to compete with big chains." },
  { word: "competent", pos: "adj.", cn: "有能力的；胜任的", ex: "She is a competent and reliable worker." },
  { word: "compile", pos: "v.", cn: "汇编；编辑", ex: "They compiled a list of useful websites." },
  { word: "complex", pos: "adj./n.", cn: "复杂的；综合体", ex: "The human brain is extremely complex." },
  { word: "component", pos: "n.", cn: "组成部分；零件", ex: "Each component of the engine was checked." },
  { word: "comprehensive", pos: "adj.", cn: "全面的；综合的", ex: "The book gives a comprehensive overview of the subject." },
  { word: "comprise", pos: "v.", cn: "包含；由…组成", ex: "The committee comprises ten members." },
  { word: "compromise", pos: "n./v.", cn: "妥协；折中", ex: "After long talks, they reached a compromise." },
  { word: "conceive", pos: "v.", cn: "构想；设想", ex: "It is hard to conceive of life without the internet." },
  { word: "concept", pos: "n.", cn: "概念；观念", ex: "The concept of freedom means different things to different people." },
  { word: "concise", pos: "adj.", cn: "简洁的；简明的", ex: "Try to keep your answer clear and concise." },
  { word: "conclude", pos: "v.", cn: "得出结论；结束", ex: "The study concluded that diet affects mood." },
  { word: "concrete", pos: "adj./n.", cn: "具体的；混凝土", ex: "We need concrete evidence, not guesses." },
  { word: "conduct", pos: "v./n.", cn: "进行；行为；指挥", ex: "Scientists conducted an experiment to test the theory." },
  { word: "confine", pos: "v.", cn: "限制；局限", ex: "The problem is not confined to one country." },
  { word: "conform", pos: "v.", cn: "遵守；符合", ex: "All products must conform to safety standards." },
  { word: "confront", pos: "v.", cn: "面对；对抗", ex: "We must confront the issue directly." },
  { word: "consensus", pos: "n.", cn: "共识；一致意见", ex: "There is a growing consensus on climate change." },
  { word: "consent", pos: "n./v.", cn: "同意；许可", ex: "You need your parents' consent to join the trip." },
  { word: "consequence", pos: "n.", cn: "后果；结果", ex: "Pollution is a serious consequence of industrialisation." },
  { word: "conservation", pos: "n.", cn: "保护；保存", ex: "Wildlife conservation is a global concern." },
  { word: "conserve", pos: "v.", cn: "保护；节约", ex: "We should conserve water during the dry season." },
  { word: "considerable", pos: "adj.", cn: "相当大的；可观的", ex: "The project required a considerable amount of time." },
  { word: "consist", pos: "v.", cn: "由…组成；在于", ex: "The team consists of five experienced doctors." },
  { word: "constant", pos: "adj.", cn: "不变的；持续的", ex: "The machine works at a constant speed." },
  { word: "constitute", pos: "v.", cn: "构成；组成", ex: "Women constitute almost half of the workforce." },
  { word: "constrain", pos: "v.", cn: "限制；约束", ex: "A small budget constrained what they could do." },
  { word: "construct", pos: "v.", cn: "建造；构建", ex: "Engineers will construct a new bridge here." },
  { word: "consult", pos: "v.", cn: "咨询；商议；查阅", ex: "You should consult a doctor about your symptoms." },
  { word: "consume", pos: "v.", cn: "消耗；消费；吃喝", ex: "Modern cars consume less fuel than older ones." },
  { word: "contagious", pos: "adj.", cn: "传染性的", ex: "The disease is highly contagious." },
  { word: "contamination", pos: "n.", cn: "污染；玷污", ex: "The water supply was at risk of contamination." },
  { word: "contemplate", pos: "v.", cn: "考虑；沉思", ex: "She is contemplating a change of career." },
  { word: "contemporary", pos: "adj./n.", cn: "当代的；同代人", ex: "The museum focuses on contemporary art." },
  { word: "context", pos: "n.", cn: "语境；背景", ex: "You should understand the word in its context." },
  { word: "contradict", pos: "v.", cn: "反驳；与…矛盾", ex: "His later statement contradicted the earlier one." },
  { word: "contrary", pos: "adj./n.", cn: "相反的；对立面", ex: "Contrary to expectations, the plan succeeded." },
  { word: "contrast", pos: "n./v.", cn: "对比；对照", ex: "There is a sharp contrast between the two cities." },
  { word: "contribute", pos: "v.", cn: "贡献；促成；捐助", ex: "Several factors contributed to the company's failure." },
  { word: "controversial", pos: "adj.", cn: "有争议的", ex: "The new policy proved highly controversial." },
  { word: "convention", pos: "n.", cn: "惯例；公约；大会", ex: "It is a social convention to shake hands." },
  { word: "conventional", pos: "adj.", cn: "传统的；常规的", ex: "Conventional methods no longer work well here." },
  { word: "convert", pos: "v.", cn: "转换；改变", ex: "They converted the old factory into flats." },
  { word: "convey", pos: "v.", cn: "传达；运送", ex: "Words alone cannot convey how I feel." },
  { word: "convince", pos: "v.", cn: "使信服；说服", ex: "She convinced me that the idea would work." },
  { word: "cooperate", pos: "v.", cn: "合作；配合", ex: "The two countries agreed to cooperate on trade." },
  { word: "coordinate", pos: "v.", cn: "协调；配合", ex: "She coordinates the work of several teams." },
  { word: "core", pos: "n./adj.", cn: "核心；要点", ex: "Honesty is at the core of his character." },
  { word: "corporate", pos: "adj.", cn: "公司的；法人的", ex: "The company is trying to improve its corporate image." },
  { word: "correspond", pos: "v.", cn: "符合；相当；通信", ex: "The results correspond closely to our predictions." },
  { word: "counterpart", pos: "n.", cn: "对应的人/物", ex: "The minister met her French counterpart." },
  { word: "crisis", pos: "n.", cn: "危机", ex: "The country is facing a serious economic crisis." },
  { word: "criterion", pos: "n.", cn: "标准（复数 criteria）", ex: "Price is not the only criterion when choosing a school." },
  { word: "crucial", pos: "adj.", cn: "至关重要的", ex: "Sleep plays a crucial role in good health." },
  { word: "cultivate", pos: "v.", cn: "培养；耕种", ex: "It takes effort to cultivate good habits." },
  { word: "cumulative", pos: "adj.", cn: "累积的；渐增的", ex: "The cumulative effect of small savings is large." },
  { word: "currency", pos: "n.", cn: "货币；通货", ex: "The dollar is the main currency for world trade." },
  { word: "current", pos: "adj./n.", cn: "当前的；水流；电流", ex: "The current situation is improving slowly." },
  { word: "curriculum", pos: "n.", cn: "课程；课程体系", ex: "The school has a broad and balanced curriculum." },
  { word: "custody", pos: "n.", cn: "拘留；监护权", ex: "The suspect is being held in custody." },
  { word: "custom", pos: "n.", cn: "习俗；惯例", ex: "Shaking hands is a common custom here." },
  { word: "debate", pos: "n./v.", cn: "辩论；争论", ex: "There is much debate about the causes of crime." },
  { word: "decade", pos: "n.", cn: "十年", ex: "The city has changed greatly over the past decade." },
  { word: "decline", pos: "v./n.", cn: "下降；衰退；婉拒", ex: "Sales have declined sharply this year." },
  { word: "dedicate", pos: "v.", cn: "致力于；献给", ex: "She dedicated her life to helping the poor." },
  { word: "deduce", pos: "v.", cn: "推断；演绎", ex: "From the evidence we can deduce what happened." },
  { word: "defect", pos: "n.", cn: "缺陷；瑕疵", ex: "The car was recalled because of a safety defect." },
  { word: "deficit", pos: "n.", cn: "赤字；不足", ex: "The government is trying to reduce the budget deficit." },
  { word: "define", pos: "v.", cn: "给…下定义；明确", ex: "It is difficult to define what success means." },
  { word: "definite", pos: "adj.", cn: "明确的；确定的", ex: "We need a definite answer by tomorrow." },
  { word: "deforestation", pos: "n.", cn: "森林砍伐", ex: "Deforestation threatens many species." },
  { word: "deliberate", pos: "adj.", cn: "故意的；深思熟虑的", ex: "It was a deliberate attempt to mislead us." },
  { word: "demographic", pos: "adj./n.", cn: "人口的；人口统计", ex: "The town has seen big demographic changes." },
  { word: "demonstrate", pos: "v.", cn: "证明；演示；示威", ex: "The study demonstrates a clear link between diet and health." },
  { word: "denote", pos: "v.", cn: "表示；意味着", ex: "A red light denotes danger." },
  { word: "dense", pos: "adj.", cn: "密集的；浓密的", ex: "The city has a dense population." },
  { word: "deny", pos: "v.", cn: "否认；拒绝给予", ex: "He denied that he had taken the money." },
  { word: "depict", pos: "v.", cn: "描绘；描述", ex: "The painting depicts a quiet country scene." },
  { word: "deprive", pos: "v.", cn: "剥夺；使丧失", ex: "Poverty deprives many children of an education." },
  { word: "derive", pos: "v.", cn: "源于；获得", ex: "Many English words derive from Latin." },
  { word: "descend", pos: "v.", cn: "下降；下来", ex: "The plane began to descend towards the airport." },
  { word: "detect", pos: "v.", cn: "察觉；检测", ex: "The device can detect very small amounts of gas." },
  { word: "deteriorate", pos: "v.", cn: "恶化；变坏", ex: "Her health deteriorated rapidly last winter." },
  { word: "determine", pos: "v.", cn: "决定；确定", ex: "Your attitude can determine your success." },
  { word: "deterrent", pos: "n.", cn: "威慑（物）", ex: "Heavy fines act as a deterrent to speeding." },
  { word: "detrimental", pos: "adj.", cn: "有害的；不利的", ex: "Smoking is detrimental to your health." },
  { word: "devastate", pos: "v.", cn: "毁灭；使极度震惊", ex: "The earthquake devastated the whole region." },
  { word: "device", pos: "n.", cn: "装置；设备", ex: "A smartphone is a useful electronic device." },
  { word: "devote", pos: "v.", cn: "致力于；奉献", ex: "He devotes most of his free time to music." },
  { word: "diagnose", pos: "v.", cn: "诊断", ex: "Doctors diagnosed the illness early." },
  { word: "diet", pos: "n.", cn: "饮食；节食", ex: "A balanced diet keeps you healthy." },
  { word: "differentiate", pos: "v.", cn: "区分；区别", ex: "It is hard to differentiate between the twins." },
  { word: "digital", pos: "adj.", cn: "数字的；数码的", ex: "We live in a digital age." },
  { word: "dilemma", pos: "n.", cn: "困境；进退两难", ex: "She faced a dilemma between work and family." },
  { word: "diminish", pos: "v.", cn: "减少；削弱", ex: "Public interest in the issue has gradually diminished." },
  { word: "diploma", pos: "n.", cn: "文凭；毕业证书", ex: "She earned a diploma in nursing." },
  { word: "discard", pos: "v.", cn: "丢弃；抛弃", ex: "People discard tonnes of plastic every day." },
  { word: "discipline", pos: "n.", cn: "纪律；学科；训练", ex: "Learning a language requires discipline." },
  { word: "disclose", pos: "v.", cn: "透露；揭露", ex: "The company refused to disclose its profits." },
  { word: "discrete", pos: "adj.", cn: "分离的；离散的", ex: "The course is divided into discrete units." },
  { word: "discriminate", pos: "v.", cn: "歧视；区分", ex: "It is illegal to discriminate against employees." },
  { word: "displace", pos: "v.", cn: "取代；迫使离开", ex: "The flood displaced thousands of people." },
  { word: "dispose", pos: "v.", cn: "处理；处置", ex: "Please dispose of the rubbish properly." },
  { word: "dispute", pos: "n./v.", cn: "争论；纠纷", ex: "The two sides are still in dispute over the land." },
  { word: "disrupt", pos: "v.", cn: "扰乱；中断", ex: "The storm disrupted train services." },
  { word: "distinct", pos: "adj.", cn: "明显的；截然不同的", ex: "There are two distinct types of customer." },
  { word: "distort", pos: "v.", cn: "扭曲；歪曲", ex: "The newspaper distorted what she actually said." },
  { word: "distribute", pos: "v.", cn: "分配；分发；分布", ex: "Volunteers distributed food to the homeless." },
  { word: "diverse", pos: "adj.", cn: "多样的；不同的", ex: "The city has a diverse population." },
  { word: "domestic", pos: "adj.", cn: "国内的；家用的", ex: "The policy mainly affects domestic markets." },
  { word: "dominate", pos: "v.", cn: "支配；主导", ex: "A few large firms dominate the industry." },
  { word: "donate", pos: "v.", cn: "捐赠；捐献", ex: "Many people donated money to the charity." },
  { word: "draft", pos: "n./v.", cn: "草稿；起草", ex: "She wrote a first draft of the essay." },
  { word: "dramatic", pos: "adj.", cn: "戏剧性的；剧烈的", ex: "There was a dramatic increase in prices." },
  { word: "drastic", pos: "adj.", cn: "激烈的；极端的", ex: "The company took drastic measures to cut costs." },
  { word: "drawback", pos: "n.", cn: "缺点；不利因素", ex: "The main drawback of the plan is its cost." },
  { word: "drought", pos: "n.", cn: "干旱", ex: "The long drought ruined the crops." },
  { word: "durable", pos: "adj.", cn: "耐用的；持久的", ex: "These boots are durable and comfortable." },
  { word: "duration", pos: "n.", cn: "持续时间", ex: "The duration of the course is six weeks." },
  { word: "dynamic", pos: "adj.", cn: "动态的；有活力的", ex: "She is a dynamic and creative leader." },
  { word: "ecology", pos: "n.", cn: "生态；生态学", ex: "Pollution threatens the ecology of the river." },
  { word: "economic", pos: "adj.", cn: "经济的", ex: "The country enjoyed rapid economic growth." },
  { word: "ecosystem", pos: "n.", cn: "生态系统", ex: "Pollution can damage a whole ecosystem." },
  { word: "efficient", pos: "adj.", cn: "高效的；有效率的", ex: "The new system is more efficient and saves time." },
  { word: "elaborate", pos: "adj./v.", cn: "复杂精细的；详细阐述", ex: "Could you elaborate on your last point?" },
  { word: "element", pos: "n.", cn: "要素；元素", ex: "Trust is a key element of any friendship." },
  { word: "eligible", pos: "adj.", cn: "符合条件的；有资格的", ex: "Only citizens are eligible to vote." },
  { word: "eliminate", pos: "v.", cn: "消除；淘汰", ex: "We aim to eliminate waste in the factory." },
  { word: "emerge", pos: "v.", cn: "出现；浮现", ex: "New evidence has emerged in the case." },
  { word: "emission", pos: "n.", cn: "排放；排放物", ex: "We must cut carbon emissions." },
  { word: "emit", pos: "v.", cn: "排放；发出", ex: "Cars emit harmful gases into the air." },
  { word: "emphasise", pos: "v.", cn: "强调；着重", ex: "The teacher emphasised the importance of revision." },
  { word: "empirical", pos: "adj.", cn: "经验的；实证的", ex: "The theory is supported by empirical evidence." },
  { word: "empower", pos: "v.", cn: "赋予权力；增强能力", ex: "Education can empower women to change their lives." },
  { word: "enable", pos: "v.", cn: "使能够；使成为可能", ex: "The internet enables people to work from home." },
  { word: "encounter", pos: "v./n.", cn: "遭遇；偶遇", ex: "We encountered several problems along the way." },
  { word: "endangered", pos: "adj.", cn: "濒危的", ex: "The panda is an endangered species." },
  { word: "endeavour", pos: "n./v.", cn: "努力；尝试", ex: "Despite their best endeavours, they failed." },
  { word: "endure", pos: "v.", cn: "忍受；持久", ex: "They had to endure great hardship." },
  { word: "enforce", pos: "v.", cn: "执行；强制实施", ex: "The police enforce the traffic laws." },
  { word: "enhance", pos: "v.", cn: "提高；增强", ex: "Good lighting can enhance the look of a room." },
  { word: "enormous", pos: "adj.", cn: "巨大的；庞大的", ex: "The project required an enormous amount of money." },
  { word: "enrich", pos: "v.", cn: "使丰富；使富裕", ex: "Travel can enrich your understanding of the world." },
  { word: "ensure", pos: "v.", cn: "确保；保证", ex: "Please ensure that the door is locked." },
  { word: "enterprise", pos: "n.", cn: "企业；事业；进取心", ex: "She runs a small but successful enterprise." },
  { word: "entity", pos: "n.", cn: "实体；存在", ex: "The two companies remain separate legal entities." },
  { word: "entrepreneur", pos: "n.", cn: "企业家", ex: "She is a successful young entrepreneur." },
  { word: "epidemic", pos: "n.", cn: "流行病；盛行", ex: "The flu epidemic spread quickly." },
  { word: "equate", pos: "v.", cn: "等同；把…等同于", ex: "People often equate wealth with happiness." },
  { word: "equip", pos: "v.", cn: "装备；配备", ex: "The lab is equipped with modern instruments." },
  { word: "equivalent", pos: "adj./n.", cn: "相等的；等价物", ex: "One mile is roughly equivalent to 1.6 kilometres." },
  { word: "eradicate", pos: "v.", cn: "根除；消灭", ex: "The country hopes to eradicate poverty." },
  { word: "erode", pos: "v.", cn: "侵蚀；逐渐削弱", ex: "Waves slowly erode the coastline." },
  { word: "essential", pos: "adj.", cn: "必要的；本质的", ex: "Water is essential for all living things." },
  { word: "establish", pos: "v.", cn: "建立；确立", ex: "The company was established in 1990." },
  { word: "estimate", pos: "v./n.", cn: "估计；估算", ex: "Experts estimate the cost at one million dollars." },
  { word: "evaluate", pos: "v.", cn: "评价；评估", ex: "We need to evaluate the results carefully." },
  { word: "evident", pos: "adj.", cn: "明显的；显而易见的", ex: "It was evident that she was tired." },
  { word: "evoke", pos: "v.", cn: "唤起；引起", ex: "The song evokes memories of my childhood." },
  { word: "evolve", pos: "v.", cn: "进化；逐渐发展", ex: "The company has evolved into a global brand." },
  { word: "exaggerate", pos: "v.", cn: "夸大；夸张", ex: "He tends to exaggerate the dangers." },
  { word: "exceed", pos: "v.", cn: "超过；超出", ex: "The cost must not exceed the budget." },
  { word: "exceptional", pos: "adj.", cn: "杰出的；异常的", ex: "She is a student of exceptional ability." },
  { word: "exclude", pos: "v.", cn: "排除；不包括", ex: "The price excludes delivery charges." },
  { word: "exhibit", pos: "v./n.", cn: "展示；展品", ex: "The museum exhibits works by local artists." },
  { word: "expand", pos: "v.", cn: "扩展；扩大", ex: "The company plans to expand into Asia." },
  { word: "expertise", pos: "n.", cn: "专业知识；专长", ex: "We lack the expertise to do this ourselves." },
  { word: "explicit", pos: "adj.", cn: "明确的；清楚的", ex: "She gave explicit instructions on what to do." },
  { word: "exploit", pos: "v.", cn: "利用；开发；剥削", ex: "We should exploit renewable energy sources." },
  { word: "exposure", pos: "n.", cn: "暴露；接触", ex: "Long exposure to the sun can damage your skin." },
  { word: "extend", pos: "v.", cn: "延伸；延长；扩展", ex: "They plan to extend the deadline by a week." },
  { word: "extensive", pos: "adj.", cn: "广泛的；大量的", ex: "The book provides extensive coverage of the topic." },
  { word: "external", pos: "adj.", cn: "外部的；外界的", ex: "The report was reviewed by an external expert." },
  { word: "extinction", pos: "n.", cn: "灭绝；消亡", ex: "Many animals are facing extinction." },
  { word: "extract", pos: "v./n.", cn: "提取；摘录", ex: "Sugar is extracted from sugar cane." },
  { word: "facilitate", pos: "v.", cn: "促进；使便利", ex: "The new road will facilitate travel between the towns." },
  { word: "faculty", pos: "n.", cn: "学院；能力；全体教员", ex: "She joined the Faculty of Science." },
  { word: "fatigue", pos: "n.", cn: "疲劳；劳累", ex: "Driver fatigue is a major cause of accidents." },
  { word: "feasible", pos: "adj.", cn: "可行的", ex: "The plan is feasible if we have enough time." },
  { word: "feature", pos: "n./v.", cn: "特征；以…为特色", ex: "Safety is an important feature of the design." },
  { word: "federal", pos: "adj.", cn: "联邦的", ex: "The issue is handled by the federal government." },
  { word: "fertile", pos: "adj.", cn: "肥沃的；多产的", ex: "The valley has very fertile soil." },
  { word: "finance", pos: "n./v.", cn: "财政；资金；资助", ex: "The project was financed by the government." },
  { word: "finite", pos: "adj.", cn: "有限的", ex: "The earth has finite natural resources." },
  { word: "flexible", pos: "adj.", cn: "灵活的；可弯曲的", ex: "We need a more flexible working schedule." },
  { word: "flood", pos: "n./v.", cn: "洪水；淹没", ex: "Heavy rain caused serious flooding." },
  { word: "flourish", pos: "v.", cn: "繁荣；茁壮成长", ex: "The arts flourished during this period." },
  { word: "fluctuate", pos: "v.", cn: "波动；起伏", ex: "Prices fluctuate according to demand." },
  { word: "foresee", pos: "v.", cn: "预见；预料", ex: "No one could foresee the consequences." },
  { word: "fossil", pos: "n.", cn: "化石", ex: "Burning fossil fuels harms the environment." },
  { word: "foster", pos: "v.", cn: "培养；促进；抚育", ex: "Schools should foster a love of learning." },
  { word: "framework", pos: "n.", cn: "框架；体系", ex: "The theory provides a framework for the research." },
  { word: "freelance", pos: "adj./v.", cn: "自由职业的", ex: "She works as a freelance designer." },
  { word: "frequent", pos: "adj.", cn: "频繁的；经常的", ex: "There are frequent buses to the city centre." },
  { word: "fruitful", pos: "adj.", cn: "富有成效的", ex: "The meeting was friendly and fruitful." },
  { word: "function", pos: "n./v.", cn: "功能；作用；运作", ex: "The main function of the heart is to pump blood." },
  { word: "fundamental", pos: "adj.", cn: "基本的；根本的", ex: "Reading is a fundamental skill." },
  { word: "furthermore", pos: "adv.", cn: "此外；而且", ex: "The plan is risky; furthermore, it is expensive." },
  { word: "gadget", pos: "n.", cn: "小器具；小装置", ex: "He loves buying the latest gadgets." },
  { word: "gender", pos: "n.", cn: "性别", ex: "The survey looked at differences between genders." },
  { word: "generate", pos: "v.", cn: "产生；生成", ex: "Wind turbines generate electricity." },
  { word: "genuine", pos: "adj.", cn: "真正的；真诚的", ex: "She showed genuine concern for the patients." },
  { word: "glacier", pos: "n.", cn: "冰川", ex: "The glacier is melting because of warmer weather." },
  { word: "globalization", pos: "n.", cn: "全球化", ex: "Globalization has changed world trade." },
  { word: "globe", pos: "n.", cn: "地球；球体", ex: "The company has offices across the globe." },
  { word: "graduate", pos: "n./v.", cn: "毕业生；毕业", ex: "She will graduate from university next year." },
  { word: "grant", pos: "v./n.", cn: "授予；拨款；承认", ex: "The university granted her a scholarship." },
  { word: "greenhouse", pos: "n.", cn: "温室", ex: "Cars produce greenhouse gases." },
  { word: "guarantee", pos: "v./n.", cn: "保证；担保", ex: "We cannot guarantee that the train will be on time." },
  { word: "guideline", pos: "n.", cn: "指导方针；准则", ex: "The government issued new safety guidelines." },
  { word: "habitat", pos: "n.", cn: "栖息地", ex: "Pollution is destroying the natural habitat of many species." },
  { word: "hardware", pos: "n.", cn: "硬件", ex: "You need better hardware to run this program." },
  { word: "hazard", pos: "n.", cn: "危险；危害", ex: "Wet floors are a hazard in the kitchen." },
  { word: "heritage", pos: "n.", cn: "遗产；传统", ex: "The city is proud of its cultural heritage." },
  { word: "hierarchy", pos: "n.", cn: "等级制度", ex: "There is a strict hierarchy within the army." },
  { word: "highlight", pos: "v./n.", cn: "强调；亮点", ex: "The report highlights the need for change." },
  { word: "hinder", pos: "v.", cn: "阻碍；妨碍", ex: "Heavy rain hindered the rescue work." },
  { word: "hostile", pos: "adj.", cn: "敌对的；不友好的", ex: "The proposal met with a hostile response." },
  { word: "hygiene", pos: "n.", cn: "卫生", ex: "Good personal hygiene helps prevent illness." },
  { word: "hypothesis", pos: "n.", cn: "假设；假说", ex: "The experiment was designed to test the hypothesis." },
  { word: "identical", pos: "adj.", cn: "完全相同的", ex: "The two copies are identical." },
  { word: "identify", pos: "v.", cn: "识别；确认", ex: "Police were unable to identify the man." },
  { word: "ideology", pos: "n.", cn: "意识形态；思想体系", ex: "The two parties have very different ideologies." },
  { word: "ignorance", pos: "n.", cn: "无知；不了解", ex: "Many accidents are caused by ignorance of the rules." },
  { word: "illustrate", pos: "v.", cn: "说明；举例；插图", ex: "Let me illustrate the point with an example." },
  { word: "immense", pos: "adj.", cn: "巨大的；极大的", ex: "The project was an immense success." },
  { word: "immigration", pos: "n.", cn: "移民；移居", ex: "The country has strict immigration laws." },
  { word: "immune", pos: "adj.", cn: "免疫的；不受影响的", ex: "Vaccines help the body become immune to disease." },
  { word: "impede", pos: "v.", cn: "阻碍；妨碍", ex: "Bad weather impeded our progress." },
  { word: "implement", pos: "v.", cn: "实施；执行", ex: "The school plans to implement the new system next year." },
  { word: "implication", pos: "n.", cn: "含意；可能的影响", ex: "The decision has serious implications for the future." },
  { word: "implicit", pos: "adj.", cn: "含蓄的；不言明的", ex: "There was an implicit threat in his words." },
  { word: "impose", pos: "v.", cn: "强加；征收", ex: "The government imposed a tax on imported goods." },
  { word: "incentive", pos: "n.", cn: "激励；动机", ex: "Tax cuts give companies an incentive to invest." },
  { word: "incidence", pos: "n.", cn: "发生率", ex: "The incidence of the disease is rising." },
  { word: "incline", pos: "v.", cn: "倾向；使倾斜", ex: "I am inclined to agree with you." },
  { word: "incorporate", pos: "v.", cn: "合并；包含", ex: "The design incorporates several new features." },
  { word: "incur", pos: "v.", cn: "招致；引起（损失等）", ex: "You may incur extra costs if you cancel." },
  { word: "indicate", pos: "v.", cn: "表明；指示", ex: "The results indicate a clear trend." },
  { word: "indigenous", pos: "adj.", cn: "本土的；土生土长的", ex: "The plant is indigenous to South America." },
  { word: "indispensable", pos: "adj.", cn: "不可或缺的", ex: "Computers are now indispensable in offices." },
  { word: "individual", pos: "n./adj.", cn: "个人；个别的", ex: "Each individual has different needs." },
  { word: "induce", pos: "v.", cn: "引起；诱导", ex: "Certain foods can induce sleep." },
  { word: "inequality", pos: "n.", cn: "不平等", ex: "There is growing inequality between rich and poor." },
  { word: "inevitable", pos: "adj.", cn: "不可避免的", ex: "Some delay now seems inevitable." },
  { word: "infection", pos: "n.", cn: "感染；传染", ex: "Wash your hands to prevent infection." },
  { word: "infer", pos: "v.", cn: "推断；推论", ex: "We can infer her mood from her tone of voice." },
  { word: "inflation", pos: "n.", cn: "通货膨胀", ex: "High inflation reduces people's spending power." },
  { word: "influence", pos: "n./v.", cn: "影响；影响力", ex: "Parents have a strong influence on their children." },
  { word: "influential", pos: "adj.", cn: "有影响力的", ex: "She is one of the most influential writers today." },
  { word: "infrastructure", pos: "n.", cn: "基础设施", ex: "The country is investing in roads and other infrastructure." },
  { word: "ingenious", pos: "adj.", cn: "巧妙的；有独创性的", ex: "He came up with an ingenious solution." },
  { word: "inhabit", pos: "v.", cn: "居住于；栖息于", ex: "Few animals can inhabit such a cold place." },
  { word: "inherent", pos: "adj.", cn: "固有的；内在的", ex: "There are inherent risks in any business." },
  { word: "inhibit", pos: "v.", cn: "抑制；阻止", ex: "Fear can inhibit learning." },
  { word: "initial", pos: "adj.", cn: "最初的；开始的", ex: "My initial reaction was one of surprise." },
  { word: "initiative", pos: "n.", cn: "主动性；倡议", ex: "She showed great initiative in solving the problem." },
  { word: "innovate", pos: "v.", cn: "创新；革新", ex: "Companies must innovate to stay competitive." },
  { word: "input", pos: "n./v.", cn: "投入；输入", ex: "We welcome input from all team members." },
  { word: "inquiry", pos: "n.", cn: "询问；调查", ex: "The police launched an inquiry into the accident." },
  { word: "insight", pos: "n.", cn: "洞察力；见解", ex: "The book offers a deep insight into human behaviour." },
  { word: "inspect", pos: "v.", cn: "检查；视察", ex: "Officials came to inspect the factory." },
  { word: "inspire", pos: "v.", cn: "激励；启发", ex: "Her speech inspired the whole audience." },
  { word: "instance", pos: "n.", cn: "例子；实例", ex: "This is just one instance of a wider problem." },
  { word: "institute", pos: "n./v.", cn: "机构；设立", ex: "He works at a research institute." },
  { word: "instruct", pos: "v.", cn: "指示；教导", ex: "The teacher instructed the class to read quietly." },
  { word: "insufficient", pos: "adj.", cn: "不足的；不够的", ex: "There was insufficient evidence to convict him." },
  { word: "integrate", pos: "v.", cn: "整合；融合", ex: "The software integrates text and images." },
  { word: "integrity", pos: "n.", cn: "正直；完整", ex: "She is a woman of great integrity." },
  { word: "intellectual", pos: "adj./n.", cn: "智力的；知识分子", ex: "Chess is an intellectual challenge." },
  { word: "intense", pos: "adj.", cn: "强烈的；紧张的", ex: "The competition is extremely intense." },
  { word: "interact", pos: "v.", cn: "互动；相互作用", ex: "Children learn by interacting with others." },
  { word: "interfere", pos: "v.", cn: "干涉；妨碍", ex: "Noise can interfere with your concentration." },
  { word: "internal", pos: "adj.", cn: "内部的；体内的", ex: "The company carried out an internal review." },
  { word: "interpret", pos: "v.", cn: "解释；口译；理解", ex: "It is hard to interpret these results." },
  { word: "interval", pos: "n.", cn: "间隔；间歇", ex: "The buses run at regular intervals." },
  { word: "intervene", pos: "v.", cn: "干预；介入", ex: "The government may intervene to stop prices rising." },
  { word: "intricate", pos: "adj.", cn: "复杂精细的", ex: "The watch has an intricate mechanism." },
  { word: "intrinsic", pos: "adj.", cn: "内在的；固有的", ex: "Reading has an intrinsic value of its own." },
  { word: "invest", pos: "v.", cn: "投资；投入", ex: "They decided to invest in new equipment." },
  { word: "investigate", pos: "v.", cn: "调查；研究", ex: "Scientists are investigating the cause of the disease." },
  { word: "invoke", pos: "v.", cn: "援引；唤起", ex: "She invoked an old law to support her case." },
  { word: "involve", pos: "v.", cn: "涉及；包含；使参与", ex: "The job involves a lot of travelling." },
  { word: "isolate", pos: "v.", cn: "隔离；孤立", ex: "Patients with the virus were isolated." },
  { word: "issue", pos: "n./v.", cn: "问题；议题；发行", ex: "Climate change is a global issue." },
  { word: "judicial", pos: "adj.", cn: "司法的；法庭的", ex: "Courts are part of the judicial system." },
  { word: "justify", pos: "v.", cn: "证明…正当；为…辩护", ex: "Nothing can justify such cruelty." },
  { word: "kindergarten", pos: "n.", cn: "幼儿园", ex: "Her son has just started kindergarten." },
  { word: "label", pos: "n./v.", cn: "标签；贴标签", ex: "Always read the label before taking medicine." },
  { word: "labour", pos: "n./v.", cn: "劳动；劳工", ex: "The factory relies on cheap labour." },
  { word: "landscape", pos: "n.", cn: "风景；景观", ex: "The painting shows a beautiful mountain landscape." },
  { word: "launch", pos: "v./n.", cn: "发射；推出；发起", ex: "The company will launch a new phone next month." },
  { word: "lecture", pos: "n./v.", cn: "讲座；演讲", ex: "Students attend lectures every morning." },
  { word: "legacy", pos: "n.", cn: "遗产；遗留", ex: "The war left a legacy of poverty." },
  { word: "legislation", pos: "n.", cn: "立法；法规", ex: "New legislation was passed to protect consumers." },
  { word: "legitimate", pos: "adj.", cn: "合法的；正当的", ex: "She has a legitimate reason to complain." },
  { word: "leisure", pos: "n.", cn: "休闲；空闲", ex: "People have more leisure time than before." },
  { word: "liable", pos: "adj.", cn: "有责任的；易于…的", ex: "The company is liable for any damage." },
  { word: "liberal", pos: "adj.", cn: "自由的；开明的；慷慨的", ex: "He holds fairly liberal views on education." },
  { word: "likewise", pos: "adv.", cn: "同样地；也", ex: "She works hard, and expects others to do likewise." },
  { word: "limitation", pos: "n.", cn: "限制；局限", ex: "We must accept the limitations of the budget." },
  { word: "linguistic", pos: "adj.", cn: "语言的；语言学的", ex: "Children develop linguistic skills very fast." },
  { word: "literacy", pos: "n.", cn: "读写能力", ex: "The programme aims to improve adult literacy." },
  { word: "logical", pos: "adj.", cn: "合乎逻辑的；合理的", ex: "It is the logical conclusion of the argument." },
  { word: "lucrative", pos: "adj.", cn: "赚钱的；获利多的", ex: "Software design can be a lucrative career." },
  { word: "maintain", pos: "v.", cn: "维持；保养；坚称", ex: "It is important to maintain a healthy diet." },
  { word: "major", pos: "adj.", cn: "主要的；重大的", ex: "Traffic is a major problem in big cities." },
  { word: "manifest", pos: "v./adj.", cn: "显现；明显的", ex: "The disease can manifest itself in many ways." },
  { word: "manipulate", pos: "v.", cn: "操纵；控制", ex: "The media can manipulate public opinion." },
  { word: "manual", pos: "adj./n.", cn: "手工的；手册", ex: "Read the manual before using the machine." },
  { word: "margin", pos: "n.", cn: "边缘；利润；差额", ex: "He won the election by a narrow margin." },
  { word: "mature", pos: "adj./v.", cn: "成熟的；成熟", ex: "She is very mature for her age." },
  { word: "maximize", pos: "v.", cn: "使最大化", ex: "The aim is to maximize profits." },
  { word: "mechanism", pos: "n.", cn: "机制；机械装置", ex: "The body has natural mechanisms to fight disease." },
  { word: "media", pos: "n.", cn: "媒体；传媒", ex: "The story was reported widely in the media." },
  { word: "mediate", pos: "v.", cn: "调解；斡旋", ex: "The UN tried to mediate between the two sides." },
  { word: "mediocre", pos: "adj.", cn: "平庸的；中等的", ex: "The film got mediocre reviews." },
  { word: "medium", pos: "n./adj.", cn: "媒介；中等的", ex: "Television is a powerful medium of communication." },
  { word: "mental", pos: "adj.", cn: "精神的；智力的", ex: "Exercise is good for your mental health." },
  { word: "merge", pos: "v.", cn: "合并；融合", ex: "The two companies decided to merge." },
  { word: "migrate", pos: "v.", cn: "迁徙；迁移", ex: "Many birds migrate south in winter." },
  { word: "minimal", pos: "adj.", cn: "最小的；极少的", ex: "The damage to the car was minimal." },
  { word: "minimize", pos: "v.", cn: "使最小化；减到最少", ex: "We must minimize the risk of accidents." },
  { word: "minor", pos: "adj.", cn: "较小的；次要的", ex: "There were only minor changes to the plan." },
  { word: "moderate", pos: "adj.", cn: "适度的；温和的", ex: "She does a moderate amount of exercise each day." },
  { word: "modify", pos: "v.", cn: "修改；调整", ex: "The design was modified to reduce costs." },
  { word: "momentum", pos: "n.", cn: "势头；动量", ex: "The campaign is gaining momentum." },
  { word: "monitor", pos: "v./n.", cn: "监控；显示器", ex: "Doctors monitor the patient's heart rate." },
  { word: "monopoly", pos: "n.", cn: "垄断；专营", ex: "The company once had a monopoly on the market." },
  { word: "moreover", pos: "adv.", cn: "此外；而且", ex: "The plan is costly; moreover, it may not work." },
  { word: "motivate", pos: "v.", cn: "激励；激发", ex: "Good teachers know how to motivate students." },
  { word: "multicultural", pos: "adj.", cn: "多元文化的", ex: "London is a multicultural city." },
  { word: "mundane", pos: "adj.", cn: "平凡的；单调的", ex: "Most of the work is fairly mundane." },
  { word: "mutual", pos: "adj.", cn: "相互的；共同的", ex: "The agreement is based on mutual respect." },
  { word: "neglect", pos: "v./n.", cn: "忽视；疏忽", ex: "He was accused of neglecting his duties." },
  { word: "negligible", pos: "adj.", cn: "微不足道的", ex: "The difference in price is negligible." },
  { word: "negotiate", pos: "v.", cn: "谈判；协商", ex: "The two sides are negotiating a peace deal." },
  { word: "network", pos: "n.", cn: "网络；网状系统", ex: "The city has a good network of public transport." },
  { word: "neutral", pos: "adj.", cn: "中立的；中性的", ex: "The country remained neutral during the war." },
  { word: "nevertheless", pos: "adv.", cn: "然而；尽管如此", ex: "The task was hard; nevertheless, they finished it." },
  { word: "norm", pos: "n.", cn: "标准；规范；常态", ex: "Working from home has become the norm for many." },
  { word: "notion", pos: "n.", cn: "概念；观念", ex: "He has no notion of how difficult it is." },
  { word: "notorious", pos: "adj.", cn: "臭名昭著的", ex: "The road is notorious for accidents." },
  { word: "notwithstanding", pos: "prep./adv.", cn: "尽管；虽然", ex: "Notwithstanding the rain, the match went ahead." },
  { word: "novel", pos: "adj./n.", cn: "新颖的；小说", ex: "They came up with a novel approach to the problem." },
  { word: "nuclear", pos: "adj.", cn: "核的；原子能的", ex: "The country relies on nuclear power for electricity." },
  { word: "numeracy", pos: "n.", cn: "计算能力；识数", ex: "The course improves both literacy and numeracy." },
  { word: "numerous", pos: "adj.", cn: "众多的；许多的", ex: "There are numerous reasons for the change." },
  { word: "nutrition", pos: "n.", cn: "营养", ex: "Good nutrition is essential for growing children." },
  { word: "obesity", pos: "n.", cn: "肥胖（症）", ex: "Childhood obesity is on the rise." },
  { word: "objective", pos: "n./adj.", cn: "目标；客观的", ex: "Our main objective is to cut costs." },
  { word: "obligation", pos: "n.", cn: "义务；责任", ex: "We have an obligation to protect the environment." },
  { word: "obscure", pos: "adj.", cn: "模糊的；晦涩的；不知名的", ex: "The meaning of the poem is rather obscure." },
  { word: "observe", pos: "v.", cn: "观察；遵守", ex: "Scientists observe how animals behave in the wild." },
  { word: "obsolete", pos: "adj.", cn: "过时的；废弃的", ex: "The technology is now almost obsolete." },
  { word: "obstacle", pos: "n.", cn: "障碍；阻碍", ex: "Lack of money is the main obstacle to the project." },
  { word: "obtain", pos: "v.", cn: "获得；得到", ex: "You can obtain the form from the office." },
  { word: "obvious", pos: "adj.", cn: "明显的；显而易见的", ex: "It is obvious that she is unhappy." },
  { word: "occupy", pos: "v.", cn: "占据；占用；居住", ex: "The meeting occupied most of the morning." },
  { word: "occur", pos: "v.", cn: "发生；出现", ex: "The accident occurred late at night." },
  { word: "offender", pos: "n.", cn: "罪犯；冒犯者", ex: "Young offenders are treated differently by the law." },
  { word: "offset", pos: "v.", cn: "抵消；弥补", ex: "Higher sales offset the rising costs." },
  { word: "offspring", pos: "n.", cn: "后代；子女", ex: "Animals work hard to protect their offspring." },
  { word: "ongoing", pos: "adj.", cn: "持续进行的", ex: "The investigation is still ongoing." },
  { word: "optimal", pos: "adj.", cn: "最佳的；最优的", ex: "We are looking for the optimal solution." },
  { word: "optimistic", pos: "adj.", cn: "乐观的", ex: "She is optimistic about the future." },
  { word: "option", pos: "n.", cn: "选择；选项", ex: "Students have the option of studying abroad." },
  { word: "organic", pos: "adj.", cn: "有机的；不用化肥的", ex: "Many people prefer to buy organic food." },
  { word: "outcome", pos: "n.", cn: "结果；成果", ex: "Nobody could predict the outcome of the election." },
  { word: "output", pos: "n.", cn: "产量；输出", ex: "Factory output rose by ten percent." },
  { word: "outweigh", pos: "v.", cn: "比…更重要；胜过", ex: "The benefits outweigh the risks." },
  { word: "overall", pos: "adj./adv.", cn: "总体的；总的来说", ex: "The overall cost was higher than expected." },
  { word: "overcome", pos: "v.", cn: "克服；战胜", ex: "She overcame many difficulties to succeed." },
  { word: "overlap", pos: "v./n.", cn: "重叠；部分相同", ex: "The two subjects overlap in several areas." },
  { word: "overlook", pos: "v.", cn: "忽视；俯瞰", ex: "We must not overlook the safety risks." },
  { word: "overseas", pos: "adj./adv.", cn: "海外的；在国外", ex: "Many students choose to study overseas." },
  { word: "overwhelm", pos: "v.", cn: "压倒；使难以承受", ex: "She was overwhelmed by the amount of work." },
  { word: "parallel", pos: "adj./n.", cn: "平行的；相似之处", ex: "There are clear parallels between the two cases." },
  { word: "parameter", pos: "n.", cn: "参数；界限", ex: "We must work within the parameters of the budget." },
  { word: "paramount", pos: "adj.", cn: "首要的；至高无上的", ex: "Safety is of paramount importance." },
  { word: "participate", pos: "v.", cn: "参与；参加", ex: "All students are encouraged to participate." },
  { word: "passive", pos: "adj.", cn: "被动的；消极的", ex: "He took a passive role in the discussion." },
  { word: "peer", pos: "n.", cn: "同龄人；同辈", ex: "Teenagers are strongly influenced by their peers." },
  { word: "penalty", pos: "n.", cn: "处罚；罚款", ex: "There is a heavy penalty for late payment." },
  { word: "perceive", pos: "v.", cn: "感知；察觉；认为", ex: "People perceive risk in different ways." },
  { word: "permanent", pos: "adj.", cn: "永久的；长期的", ex: "She is looking for a permanent job." },
  { word: "persist", pos: "v.", cn: "坚持；持续", ex: "If symptoms persist, see a doctor." },
  { word: "perspective", pos: "n.", cn: "视角；观点", ex: "Try to see the issue from another perspective." },
  { word: "persuade", pos: "v.", cn: "说服；劝说", ex: "We persuaded her to join the team." },
  { word: "phase", pos: "n.", cn: "阶段；时期", ex: "The project entered its final phase." },
  { word: "phenomenon", pos: "n.", cn: "现象（复数 phenomena）", ex: "Global warming is a worldwide phenomenon." },
  { word: "philosophy", pos: "n.", cn: "哲学；理念", ex: "Her philosophy of life is to stay positive." },
  { word: "pioneer", pos: "n./v.", cn: "先驱；开拓", ex: "She was a pioneer in the field of medicine." },
  { word: "plagiarism", pos: "n.", cn: "剽窃；抄袭", ex: "The university has strict rules against plagiarism." },
  { word: "plausible", pos: "adj.", cn: "貌似合理的", ex: "Her explanation sounded plausible." },
  { word: "policy", pos: "n.", cn: "政策；方针", ex: "The government introduced a new energy policy." },
  { word: "pollution", pos: "n.", cn: "污染", ex: "Air pollution is a serious problem in big cities." },
  { word: "portion", pos: "n.", cn: "部分；一份", ex: "A large portion of the budget goes to salaries." },
  { word: "pose", pos: "v.", cn: "造成；摆姿势；提出", ex: "Pollution poses a serious threat to health." },
  { word: "potential", pos: "adj./n.", cn: "潜在的；潜力", ex: "The plan has the potential to save money." },
  { word: "poverty", pos: "n.", cn: "贫困", ex: "Millions of people still live in poverty." },
  { word: "practical", pos: "adj.", cn: "实际的；实用的", ex: "We need practical solutions, not just ideas." },
  { word: "precede", pos: "v.", cn: "在…之前；先于", ex: "A short speech preceded the dinner." },
  { word: "precise", pos: "adj.", cn: "精确的；准确的", ex: "Can you give me the precise figures?" },
  { word: "predict", pos: "v.", cn: "预测；预言", ex: "It is hard to predict how people will vote." },
  { word: "predominant", pos: "adj.", cn: "主要的；占主导的", ex: "Farming is the predominant activity in the region." },
  { word: "prejudice", pos: "n.", cn: "偏见；成见", ex: "We must fight against racial prejudice." },
  { word: "preliminary", pos: "adj.", cn: "初步的；预备的", ex: "Preliminary results look promising." },
  { word: "premise", pos: "n.", cn: "前提；假定", ex: "The argument rests on a false premise." },
  { word: "preserve", pos: "v.", cn: "保护；保存", ex: "We must preserve these ancient buildings." },
  { word: "presume", pos: "v.", cn: "假定；推测", ex: "I presume the meeting is still on." },
  { word: "prevail", pos: "v.", cn: "盛行；占上风", ex: "In the end, common sense prevailed." },
  { word: "prevalent", pos: "adj.", cn: "普遍的；流行的", ex: "This belief was prevalent in the past." },
  { word: "previous", pos: "adj.", cn: "先前的；以前的", ex: "She has no previous experience of this work." },
  { word: "primary", pos: "adj.", cn: "主要的；初级的", ex: "Our primary concern is safety." },
  { word: "principle", pos: "n.", cn: "原则；原理", ex: "He refused to lie on principle." },
  { word: "prior", pos: "adj.", cn: "在前的；优先的", ex: "No prior knowledge of the subject is needed." },
  { word: "priority", pos: "n.", cn: "优先；优先事项", ex: "Safety should be our top priority." },
  { word: "proceed", pos: "v.", cn: "继续进行；着手", ex: "After a short break, the meeting proceeded." },
  { word: "productivity", pos: "n.", cn: "生产力；生产率", ex: "New machines increased productivity." },
  { word: "profit", pos: "n./v.", cn: "利润；获利", ex: "The company made a large profit last year." },
  { word: "profound", pos: "adj.", cn: "深刻的；深远的", ex: "The war had a profound effect on society." },
  { word: "prohibit", pos: "v.", cn: "禁止", ex: "The law prohibits smoking in public places." },
  { word: "project", pos: "n./v.", cn: "项目；预测；投射", ex: "Sales are projected to rise next year." },
  { word: "prominent", pos: "adj.", cn: "突出的；著名的", ex: "She is a prominent figure in politics." },
  { word: "promote", pos: "v.", cn: "促进；提升；推广", ex: "The campaign aims to promote healthy eating." },
  { word: "prompt", pos: "v./adj.", cn: "促使；及时的", ex: "The news prompted an immediate response." },
  { word: "prone", pos: "adj.", cn: "易于…的；有…倾向的", ex: "He is prone to making careless mistakes." },
  { word: "propaganda", pos: "n.", cn: "宣传（常含贬义）", ex: "The posters were a form of political propaganda." },
  { word: "proportion", pos: "n.", cn: "比例；部分", ex: "A high proportion of students passed the exam." },
  { word: "prospect", pos: "n.", cn: "前景；可能性", ex: "There is little prospect of a quick recovery." },
  { word: "prosper", pos: "v.", cn: "繁荣；兴旺", ex: "The business prospered during the boom years." },
  { word: "prosperity", pos: "n.", cn: "繁荣；兴旺", ex: "Trade brought wealth and prosperity to the city." },
  { word: "protocol", pos: "n.", cn: "协议；规程；礼仪", ex: "Staff must follow strict safety protocols." },
  { word: "prototype", pos: "n.", cn: "原型；样品", ex: "The company built a prototype of the new car." },
  { word: "prove", pos: "v.", cn: "证明；证实", ex: "The new method proved very effective." },
  { word: "provoke", pos: "v.", cn: "激起；挑衅", ex: "The decision provoked an angry reaction." },
  { word: "publication", pos: "n.", cn: "出版；出版物", ex: "The publication of the report caused a stir." },
  { word: "pursue", pos: "v.", cn: "追求；从事", ex: "She decided to pursue a career in medicine." },
  { word: "qualification", pos: "n.", cn: "资格；资历", ex: "The job requires a teaching qualification." },
  { word: "qualify", pos: "v.", cn: "取得资格；限定", ex: "She qualified as a teacher last year." },
  { word: "quote", pos: "v./n.", cn: "引用；报价", ex: "He quoted a famous line from the poem." },
  { word: "radical", pos: "adj.", cn: "激进的；根本的", ex: "The company made radical changes to its structure." },
  { word: "random", pos: "adj.", cn: "随机的；任意的", ex: "The names were chosen at random." },
  { word: "range", pos: "n./v.", cn: "范围；幅度；变动", ex: "The shop sells a wide range of products." },
  { word: "rational", pos: "adj.", cn: "理性的；合理的", ex: "We need to make a rational decision." },
  { word: "react", pos: "v.", cn: "反应；起反应", ex: "How did she react to the news?" },
  { word: "realm", pos: "n.", cn: "领域；王国", ex: "This idea belongs to the realm of science fiction." },
  { word: "reasonable", pos: "adj.", cn: "合理的；通情达理的", ex: "The price seems reasonable to me." },
  { word: "recession", pos: "n.", cn: "经济衰退", ex: "Many people lost their jobs during the recession." },
  { word: "recipient", pos: "n.", cn: "接受者；领受者", ex: "She was the recipient of a major award." },
  { word: "recognize", pos: "v.", cn: "认出；承认", ex: "I didn't recognize you with your new haircut." },
  { word: "recommend", pos: "v.", cn: "推荐；建议", ex: "Can you recommend a good restaurant?" },
  { word: "reconcile", pos: "v.", cn: "调和；使和解", ex: "It is hard to reconcile work and family life." },
  { word: "recover", pos: "v.", cn: "恢复；找回", ex: "She is slowly recovering from her illness." },
  { word: "recruit", pos: "v.", cn: "招募；招聘", ex: "The company plans to recruit more staff." },
  { word: "recycle", pos: "v.", cn: "回收利用", ex: "We should recycle paper and glass." },
  { word: "reduce", pos: "v.", cn: "减少；降低", ex: "We must reduce our energy consumption." },
  { word: "redundant", pos: "adj.", cn: "多余的；被裁员的", ex: "The information in the second paragraph is redundant." },
  { word: "refine", pos: "v.", cn: "提炼；改进", ex: "They refined the design after testing it." },
  { word: "reflect", pos: "v.", cn: "反映；反思；反射", ex: "The results reflect the quality of the teaching." },
  { word: "reform", pos: "n./v.", cn: "改革；改良", ex: "The government promised to reform the health system." },
  { word: "refrain", pos: "v.", cn: "克制；忍住", ex: "Please refrain from smoking in the building." },
  { word: "refuge", pos: "n.", cn: "避难所；庇护", ex: "The cave provided refuge from the storm." },
  { word: "regardless", pos: "adv.", cn: "不管；无论如何", ex: "He went ahead regardless of the risks." },
  { word: "regime", pos: "n.", cn: "政权；制度", ex: "The country was ruled by a military regime." },
  { word: "region", pos: "n.", cn: "地区；区域", ex: "The region is famous for its wine." },
  { word: "register", pos: "v./n.", cn: "登记；注册", ex: "You must register before using the service." },
  { word: "regulate", pos: "v.", cn: "管理；调节", ex: "The body regulates its own temperature." },
  { word: "rehabilitation", pos: "n.", cn: "康复；改造", ex: "The programme focuses on the rehabilitation of offenders." },
  { word: "reinforce", pos: "v.", cn: "加强；强化", ex: "The results reinforce our earlier findings." },
  { word: "reject", pos: "v.", cn: "拒绝；驳回", ex: "The committee rejected the proposal." },
  { word: "relevant", pos: "adj.", cn: "相关的；切题的", ex: "Please provide all relevant documents." },
  { word: "reliable", pos: "adj.", cn: "可靠的；可信赖的", ex: "We need a reliable source of information." },
  { word: "reluctant", pos: "adj.", cn: "不情愿的；勉强的", ex: "He was reluctant to admit his mistake." },
  { word: "rely", pos: "v.", cn: "依赖；依靠", ex: "Many people rely on cars to get to work." },
  { word: "remarkable", pos: "adj.", cn: "显著的；非凡的", ex: "She made a remarkable recovery." },
  { word: "remedy", pos: "n./v.", cn: "疗法；补救", ex: "There is no easy remedy for this problem." },
  { word: "remove", pos: "v.", cn: "移除；去掉", ex: "Please remove your shoes before entering." },
  { word: "render", pos: "v.", cn: "使成为；提供；呈现", ex: "The injury rendered him unable to work." },
  { word: "renew", pos: "v.", cn: "更新；续订", ex: "You need to renew your passport." },
  { word: "renewable", pos: "adj.", cn: "可再生的", ex: "Solar power is a renewable energy source." },
  { word: "replace", pos: "v.", cn: "取代；替换", ex: "Machines have replaced many workers." },
  { word: "represent", pos: "v.", cn: "代表；表示", ex: "These figures represent a big improvement." },
  { word: "reputation", pos: "n.", cn: "名声；声誉", ex: "The school has an excellent reputation." },
  { word: "require", pos: "v.", cn: "需要；要求", ex: "The job requires a lot of patience." },
  { word: "research", pos: "n./v.", cn: "研究；调查", ex: "She is doing research into renewable energy." },
  { word: "resemble", pos: "v.", cn: "类似于；像", ex: "The boy closely resembles his father." },
  { word: "reside", pos: "v.", cn: "居住；存在于", ex: "Most students reside near the campus." },
  { word: "resign", pos: "v.", cn: "辞职；放弃", ex: "He decided to resign from his position." },
  { word: "resilient", pos: "adj.", cn: "有韧性的；适应力强的", ex: "Children are often very resilient." },
  { word: "resist", pos: "v.", cn: "抵抗；抵制；忍住", ex: "I couldn't resist buying the book." },
  { word: "resolve", pos: "v.", cn: "解决；下决心", ex: "They managed to resolve the dispute peacefully." },
  { word: "resource", pos: "n.", cn: "资源", ex: "Water is a precious resource." },
  { word: "respective", pos: "adj.", cn: "各自的；分别的", ex: "The students returned to their respective rooms." },
  { word: "respond", pos: "v.", cn: "回应；作出反应", ex: "She did not respond to my email." },
  { word: "restore", pos: "v.", cn: "恢复；修复", ex: "The old painting was carefully restored." },
  { word: "restrain", pos: "v.", cn: "抑制；约束", ex: "He could hardly restrain his anger." },
  { word: "restrict", pos: "v.", cn: "限制；约束", ex: "The new rules restrict the use of cars." },
  { word: "retain", pos: "v.", cn: "保留；保持", ex: "The company struggles to retain skilled staff." },
  { word: "retirement", pos: "n.", cn: "退休", ex: "He took early retirement at sixty." },
  { word: "retrieve", pos: "v.", cn: "取回；检索", ex: "You can retrieve the file from the backup." },
  { word: "reveal", pos: "v.", cn: "揭示；透露", ex: "The survey revealed some surprising results." },
  { word: "revenue", pos: "n.", cn: "收入；税收", ex: "Advertising is the main source of revenue." },
  { word: "reverse", pos: "v./adj.", cn: "颠倒；相反的", ex: "It is hard to reverse the damage done to nature." },
  { word: "revise", pos: "v.", cn: "修订；复习", ex: "Students should revise before the exam." },
  { word: "revive", pos: "v.", cn: "复兴；使复苏", ex: "The festival was revived after many years." },
  { word: "revolution", pos: "n.", cn: "革命；变革", ex: "The internet caused a revolution in communication." },
  { word: "rigid", pos: "adj.", cn: "僵硬的；严格的", ex: "The school has rigid rules about uniforms." },
  { word: "rigorous", pos: "adj.", cn: "严格的；严密的", ex: "The product went through rigorous testing." },
  { word: "ritual", pos: "n.", cn: "仪式；例行公事", ex: "The ceremony follows an ancient ritual." },
  { word: "robust", pos: "adj.", cn: "强健的；稳健的", ex: "The economy remains fairly robust." },
  { word: "role", pos: "n.", cn: "角色；作用", ex: "Parents play a key role in a child's education." },
  { word: "route", pos: "n.", cn: "路线；途径", ex: "We took the shortest route to the city." },
  { word: "routine", pos: "n./adj.", cn: "常规；例行的", ex: "Exercise is part of my daily routine." },
  { word: "rural", pos: "adj.", cn: "农村的；乡村的", ex: "Many young people leave rural areas for the city." },
  { word: "sacrifice", pos: "n./v.", cn: "牺牲；献身", ex: "Parents often sacrifice a lot for their children." },
  { word: "salary", pos: "n.", cn: "薪水；工资", ex: "She earns a good monthly salary." },
  { word: "scarce", pos: "adj.", cn: "稀缺的；不足的", ex: "Fresh water is scarce in the desert." },
  { word: "scenario", pos: "n.", cn: "情景；设想", ex: "Let us consider the worst-case scenario." },
  { word: "scheme", pos: "n.", cn: "计划；方案", ex: "The government launched a new housing scheme." },
  { word: "scholarship", pos: "n.", cn: "奖学金；学问", ex: "She won a scholarship to study in the UK." },
  { word: "scope", pos: "n.", cn: "范围；余地", ex: "The topic is beyond the scope of this essay." },
  { word: "scrutiny", pos: "n.", cn: "仔细检查；审查", ex: "The plan came under close scrutiny." },
  { word: "sector", pos: "n.", cn: "部门；行业", ex: "Many jobs were created in the service sector." },
  { word: "secure", pos: "adj./v.", cn: "安全的；获得；固定", ex: "She finally secured a place at university." },
  { word: "sedentary", pos: "adj.", cn: "久坐的；缺乏运动的", ex: "A sedentary lifestyle can harm your health." },
  { word: "seek", pos: "v.", cn: "寻求；寻找", ex: "Many people seek advice online." },
  { word: "segment", pos: "n.", cn: "部分；环节", ex: "The market is divided into several segments." },
  { word: "seldom", pos: "adv.", cn: "很少；不常", ex: "He seldom watches television." },
  { word: "semester", pos: "n.", cn: "学期", ex: "The course lasts one semester." },
  { word: "seminar", pos: "n.", cn: "研讨会；讨论课", ex: "We discussed the topic in a small seminar." },
  { word: "sensible", pos: "adj.", cn: "明智的；合理的", ex: "It would be sensible to book early." },
  { word: "sequence", pos: "n.", cn: "顺序；序列", ex: "The events happened in a strange sequence." },
  { word: "shift", pos: "n./v.", cn: "转变；轮班", ex: "There has been a shift in public opinion." },
  { word: "shrink", pos: "v.", cn: "收缩；缩小", ex: "The economy shrank for the second year." },
  { word: "significant", pos: "adj.", cn: "重要的；显著的", ex: "There has been a significant increase in online shopping." },
  { word: "simulate", pos: "v.", cn: "模拟；假装", ex: "The software can simulate real flying conditions." },
  { word: "simultaneous", pos: "adj.", cn: "同时的；同时发生的", ex: "The two events were almost simultaneous." },
  { word: "software", pos: "n.", cn: "软件", ex: "The company develops educational software." },
  { word: "sophisticated", pos: "adj.", cn: "复杂精密的；老练的", ex: "The factory uses sophisticated machinery." },
  { word: "span", pos: "n./v.", cn: "跨度；持续；横跨", ex: "The bridge spans a wide river." },
  { word: "specific", pos: "adj.", cn: "具体的；特定的", ex: "Could you be more specific about the dates?" },
  { word: "spectrum", pos: "n.", cn: "范围；光谱", ex: "The policy has support across the political spectrum." },
  { word: "speculate", pos: "v.", cn: "推测；投机", ex: "Reporters speculated about the reasons for her absence." },
  { word: "sphere", pos: "n.", cn: "领域；球体", ex: "She is well known in the sphere of education." },
  { word: "spontaneous", pos: "adj.", cn: "自发的；自然的", ex: "The crowd broke into spontaneous applause." },
  { word: "stable", pos: "adj.", cn: "稳定的；牢固的", ex: "The patient is now in a stable condition." },
  { word: "stagnant", pos: "adj.", cn: "停滞的；不流动的", ex: "The economy has remained stagnant for years." },
  { word: "stake", pos: "n.", cn: "利害关系；股份", ex: "Many jobs are at stake if the factory closes." },
  { word: "stance", pos: "n.", cn: "立场；态度", ex: "The party softened its stance on the issue." },
  { word: "standard", pos: "n./adj.", cn: "标准；规范的", ex: "The hotel offers a high standard of service." },
  { word: "statistic", pos: "n.", cn: "统计数据", ex: "The statistics show a fall in crime." },
  { word: "status", pos: "n.", cn: "地位；状态", ex: "The job gave him a higher social status." },
  { word: "steady", pos: "adj.", cn: "稳定的；平稳的", ex: "There has been a steady rise in prices." },
  { word: "stereotype", pos: "n./v.", cn: "刻板印象", ex: "The film challenges common stereotypes." },
  { word: "stimulate", pos: "v.", cn: "刺激；激励", ex: "Lower taxes may stimulate the economy." },
  { word: "straightforward", pos: "adj.", cn: "简单明了的；直率的", ex: "The instructions are clear and straightforward." },
  { word: "strategy", pos: "n.", cn: "策略；战略", ex: "The firm needs a new marketing strategy." },
  { word: "strengthen", pos: "v.", cn: "加强；增强", ex: "Exercise helps to strengthen the muscles." },
  { word: "strict", pos: "adj.", cn: "严格的；严厉的", ex: "The school has strict rules about attendance." },
  { word: "striking", pos: "adj.", cn: "显著的；引人注目的", ex: "There is a striking difference between the two." },
  { word: "stringent", pos: "adj.", cn: "严格的；严厉的", ex: "The factory follows stringent safety rules." },
  { word: "structure", pos: "n./v.", cn: "结构；构造", ex: "The essay has a clear structure." },
  { word: "struggle", pos: "v./n.", cn: "挣扎；奋斗", ex: "Many families struggle to pay their bills." },
  { word: "submit", pos: "v.", cn: "提交；屈服", ex: "Please submit your application by Friday." },
  { word: "subsequent", pos: "adj.", cn: "随后的；后来的", ex: "Subsequent events proved him right." },
  { word: "subsidy", pos: "n.", cn: "补贴；津贴", ex: "Farmers receive subsidies from the government." },
  { word: "substantial", pos: "adj.", cn: "大量的；实质的", ex: "She made a substantial contribution to the project." },
  { word: "substitute", pos: "n./v.", cn: "替代品；替代", ex: "You can substitute oil for butter in this recipe." },
  { word: "subtle", pos: "adj.", cn: "微妙的；细微的", ex: "There is a subtle difference between the two words." },
  { word: "suburb", pos: "n.", cn: "郊区", ex: "They moved to a quiet suburb outside the city." },
  { word: "sufficient", pos: "adj.", cn: "足够的；充足的", ex: "We do not have sufficient evidence." },
  { word: "surgery", pos: "n.", cn: "外科手术", ex: "He needs surgery on his knee." },
  { word: "surplus", pos: "n./adj.", cn: "盈余；过剩的", ex: "The country has a trade surplus this year." },
  { word: "surveillance", pos: "n.", cn: "监视；监控", ex: "There are surveillance cameras in the street." },
  { word: "sustain", pos: "v.", cn: "维持；支撑", ex: "It is hard to sustain such fast growth." },
  { word: "sustainable", pos: "adj.", cn: "可持续的", ex: "We need a more sustainable way of living." },
  { word: "syllabus", pos: "n.", cn: "教学大纲", ex: "The syllabus covers grammar and vocabulary." },
  { word: "symbol", pos: "n.", cn: "象征；符号", ex: "The dove is a symbol of peace." },
  { word: "symptom", pos: "n.", cn: "症状；征兆", ex: "A high fever is a common symptom of the flu." },
  { word: "tackle", pos: "v.", cn: "处理；对付", ex: "The government must tackle the problem of poverty." },
  { word: "tangible", pos: "adj.", cn: "有形的；切实的", ex: "The project produced tangible benefits." },
  { word: "tedious", pos: "adj.", cn: "乏味的；冗长的", ex: "Filling in forms can be a tedious task." },
  { word: "temporary", pos: "adj.", cn: "临时的；暂时的", ex: "She found a temporary job for the summer." },
  { word: "tendency", pos: "n.", cn: "趋势；倾向", ex: "There is a tendency for prices to rise in winter." },
  { word: "tense", pos: "adj./n.", cn: "紧张的；时态", ex: "The atmosphere in the room was very tense." },
  { word: "terminate", pos: "v.", cn: "终止；结束", ex: "The contract was terminated early." },
  { word: "theme", pos: "n.", cn: "主题；题目", ex: "The main theme of the book is freedom." },
  { word: "theoretical", pos: "adj.", cn: "理论的；理论上的", ex: "The course covers both theoretical and practical skills." },
  { word: "therapy", pos: "n.", cn: "治疗；疗法", ex: "She is having physical therapy after the injury." },
  { word: "thereby", pos: "adv.", cn: "从而；因此", ex: "She saved money, thereby reaching her goal." },
  { word: "thorough", pos: "adj.", cn: "彻底的；细致的", ex: "The police made a thorough search of the house." },
  { word: "threshold", pos: "n.", cn: "门槛；临界点", ex: "Income above this threshold is taxed." },
  { word: "thrive", pos: "v.", cn: "茁壮成长；繁荣", ex: "Plants thrive in warm, wet conditions." },
  { word: "tolerate", pos: "v.", cn: "容忍；忍受", ex: "The school will not tolerate bullying." },
  { word: "trace", pos: "v./n.", cn: "追踪；痕迹", ex: "Police were able to trace the call." },
  { word: "tradition", pos: "n.", cn: "传统；惯例", ex: "It is a tradition to give gifts at the festival." },
  { word: "trait", pos: "n.", cn: "特征；特性", ex: "Honesty is one of her best traits." },
  { word: "transfer", pos: "v./n.", cn: "转移；转让；调动", ex: "He was transferred to another department." },
  { word: "transform", pos: "v.", cn: "转变；改造", ex: "The internet has transformed the way we shop." },
  { word: "transition", pos: "n.", cn: "过渡；转变", ex: "The transition to the new system took time." },
  { word: "transmit", pos: "v.", cn: "传送；传播", ex: "The disease is transmitted through water." },
  { word: "transparent", pos: "adj.", cn: "透明的；清晰的", ex: "The process should be open and transparent." },
  { word: "transport", pos: "n./v.", cn: "运输；交通工具", ex: "Public transport in the city is cheap and reliable." },
  { word: "tremendous", pos: "adj.", cn: "巨大的；极好的", ex: "She made a tremendous effort to succeed." },
  { word: "trigger", pos: "v./n.", cn: "触发；引发", ex: "The news triggered a sharp fall in share prices." },
  { word: "trivial", pos: "adj.", cn: "微不足道的；琐碎的", ex: "Do not waste time on trivial details." },
  { word: "tuition", pos: "n.", cn: "学费；教学", ex: "University tuition fees keep rising." },
  { word: "tutor", pos: "n./v.", cn: "导师；辅导", ex: "He works as a private tutor in maths." },
  { word: "ubiquitous", pos: "adj.", cn: "无处不在的", ex: "Mobile phones are now ubiquitous." },
  { word: "ultimate", pos: "adj.", cn: "最终的；根本的", ex: "Our ultimate aim is world peace." },
  { word: "undergo", pos: "v.", cn: "经历；遭受", ex: "The city has undergone huge changes." },
  { word: "undergraduate", pos: "n.", cn: "本科生", ex: "He is an undergraduate studying physics." },
  { word: "underlying", pos: "adj.", cn: "潜在的；根本的", ex: "We need to find the underlying cause of the problem." },
  { word: "undermine", pos: "v.", cn: "削弱；损害", ex: "The scandal undermined public trust in the government." },
  { word: "undertake", pos: "v.", cn: "着手；承担", ex: "The company undertook a major research project." },
  { word: "unemployment", pos: "n.", cn: "失业", ex: "Unemployment rose during the recession." },
  { word: "uniform", pos: "adj./n.", cn: "统一的；制服", ex: "All the houses are of uniform size." },
  { word: "unify", pos: "v.", cn: "统一；联合", ex: "A common language helps to unify the country." },
  { word: "unique", pos: "adj.", cn: "独特的；唯一的", ex: "Each person's fingerprints are unique." },
  { word: "universal", pos: "adj.", cn: "普遍的；通用的", ex: "Music has a universal appeal." },
  { word: "unprecedented", pos: "adj.", cn: "前所未有的", ex: "The country faced an unprecedented crisis." },
  { word: "urban", pos: "adj.", cn: "城市的；都市的", ex: "More people are moving to urban areas." },
  { word: "urbanization", pos: "n.", cn: "城市化", ex: "Rapid urbanization put pressure on housing." },
  { word: "urge", pos: "v./n.", cn: "敦促；强烈愿望", ex: "Doctors urge people to eat less sugar." },
  { word: "utilize", pos: "v.", cn: "利用；使用", ex: "We should fully utilize the available resources." },
  { word: "vaccine", pos: "n.", cn: "疫苗", ex: "Scientists developed a vaccine for the disease." },
  { word: "vague", pos: "adj.", cn: "模糊的；含糊的", ex: "He gave only a vague answer." },
  { word: "valid", pos: "adj.", cn: "有效的；正当的", ex: "Your ticket is valid for one month." },
  { word: "vanish", pos: "v.", cn: "消失；不见", ex: "The ship vanished into the fog." },
  { word: "variable", pos: "n./adj.", cn: "变量；多变的", ex: "The weather here is highly variable." },
  { word: "vary", pos: "v.", cn: "变化；不同", ex: "Prices vary from shop to shop." },
  { word: "vast", pos: "adj.", cn: "广阔的；巨大的", ex: "The desert covers a vast area." },
  { word: "vehicle", pos: "n.", cn: "车辆；交通工具；媒介", ex: "Electric vehicles are becoming more popular." },
  { word: "venture", pos: "n./v.", cn: "冒险事业；敢于", ex: "The business was a risky venture." },
  { word: "verify", pos: "v.", cn: "核实；证实", ex: "We need to verify the accuracy of the data." },
  { word: "versatile", pos: "adj.", cn: "多才多艺的；多用途的", ex: "She is a versatile actress." },
  { word: "via", pos: "prep.", cn: "经由；通过", ex: "We flew to Paris via London." },
  { word: "viable", pos: "adj.", cn: "可行的；能存活的", ex: "Solar power is now a viable option." },
  { word: "vibrant", pos: "adj.", cn: "充满活力的；鲜艳的", ex: "The city has a vibrant cultural life." },
  { word: "vicinity", pos: "n.", cn: "附近；周围地区", ex: "There are several shops in the vicinity." },
  { word: "victim", pos: "n.", cn: "受害者；牺牲品", ex: "The charity helps victims of crime." },
  { word: "violate", pos: "v.", cn: "违反；侵犯", ex: "The company violated safety rules." },
  { word: "virtual", pos: "adj.", cn: "虚拟的；几乎的", ex: "The class takes place in a virtual classroom." },
  { word: "virtue", pos: "n.", cn: "美德；优点", ex: "Patience is a virtue." },
  { word: "visible", pos: "adj.", cn: "可见的；明显的", ex: "The mountains were clearly visible in the distance." },
  { word: "vision", pos: "n.", cn: "视力；远见；愿景", ex: "She has a clear vision for the future." },
  { word: "visual", pos: "adj.", cn: "视觉的", ex: "The film has stunning visual effects." },
  { word: "vital", pos: "adj.", cn: "至关重要的；必不可少的", ex: "Water is vital for survival." },
  { word: "vivid", pos: "adj.", cn: "生动的；鲜明的", ex: "She gave a vivid description of the scene." },
  { word: "vocational", pos: "adj.", cn: "职业的；专业的", ex: "Many students choose vocational training." },
  { word: "volume", pos: "n.", cn: "体积；音量；卷", ex: "The volume of traffic has increased." },
  { word: "voluntary", pos: "adj.", cn: "自愿的；志愿的", ex: "She does voluntary work at the hospital." },
  { word: "vulnerable", pos: "adj.", cn: "脆弱的；易受伤的", ex: "Young children are especially vulnerable to the disease." },
  { word: "wage", pos: "n.", cn: "工资（按时/周计）", ex: "The government raised the minimum wage." },
  { word: "welfare", pos: "n.", cn: "福利；幸福", ex: "The state provides welfare for the unemployed." },
  { word: "wellbeing", pos: "n.", cn: "幸福；健康", ex: "The company cares about staff wellbeing." },
  { word: "widespread", pos: "adj.", cn: "普遍的；广泛的", ex: "There is widespread support for the plan." },
  { word: "wildlife", pos: "n.", cn: "野生动物", ex: "The park is home to a variety of wildlife." },
  { word: "withdraw", pos: "v.", cn: "撤回；取款；退出", ex: "She withdrew some money from the bank." },
  { word: "witness", pos: "n./v.", cn: "目击者；目击", ex: "Several people witnessed the accident." },
  { word: "workforce", pos: "n.", cn: "劳动力；全体员工", ex: "Half the workforce is employed part-time." },
  { word: "yield", pos: "v./n.", cn: "产生；屈服；产量", ex: "The investment yielded a high return." }
];

// 写作练习题（AI 风格练习题，非真题）
const WRITING_PROMPTS = {
  task2: [
    "Some people think university education should be free for all students. To what extent do you agree or disagree?",
    "Many people believe that social media does more harm than good. Discuss both views and give your own opinion.",
    "Some argue that governments should invest more in public transport than in roads. Do you agree or disagree?"
  ],
  task1: [
    "The chart below shows the percentage of households with internet access in three countries from 2000 to 2020. Summarise the information.",
    "The table shows the average daily water use per person in four cities. Summarise the main features and make comparisons."
  ]
};

// 每日任务模板（按是否为"写作日"轮换）
const DAILY_TASKS = {
  base: [
    { id: "vocab", text: "背 50 个新单词" },
    { id: "test", text: "完成 5 次单词测试" },
    { id: "review", text: "复习 30 个旧词" }
  ],
  writingDay: { id: "writing", text: "写 2 篇作文并提交批改" }
};

// 备考阶段（按距离考试的周数划分）
const PLAN_STAGES = [
  { minWeeksLeft: 9, name: "基础夯实期", focus: "打牢词汇与语法，养成每日打卡习惯" },
  { minWeeksLeft: 5, name: "强化提升期", focus: "扩充学术词汇，规律练习作文与批改" },
  { minWeeksLeft: 2, name: "冲刺突破期", focus: "高频题型集中训练，针对弱项补强" },
  { minWeeksLeft: 0, name: "考前模考期", focus: "限时模考、回顾错题、保持手感" }
];

if (typeof module !== "undefined") {
  module.exports = { SEED_WORDS, WRITING_PROMPTS, DAILY_TASKS, PLAN_STAGES };
}
